---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://davidcai.github.io/blog"
canonifyurls: true
title: "David Cai"
params:
  MastheadTitle: "dcai | blog"
disqusShortname: "davidcai"
...
